### ISSUE TITLE
Unable to get script to work

### ISSUE THREAD

**Issue by jdchaiken** [alexkross/swipam-script#1]
Script does not work at all for me.  Also running script by itself with --list param does nothing even if the last line is replaced with a call to the Inventory class. 

Additionally entering incorrect IP or credentials does not trigger an error.

I have a similar inventory that I've been using/working on if you are interested.  It pulls from the NPM database and not IPAM.  I was hoping to look at yours and see if it works better or get ideas to improve mine.  

jdchaiken/solarwinds-inventory if you are interested

**Output**
 ansible -m debug -a "msg={{hostvars[inventory_hostname]|dict2items|rejectattr(\"key\", \"eq\", \"groups\")|list|items2dict}}" -i swipam.py  all

 [WARNING]:  * Failed to parse /root/swipam-script/swipam.py with script plugin: failed to parse 
executable inventory script results from /root/swipam-script/swipam.py: needs to be a json dict

 [WARNING]:  * Failed to parse /root/swipam-script/swipam.py with ini plugin: /root/swipam-script/swipam.py:17: Expected key=value host variable assignment, got: sys

 [WARNING]: Unable to parse /root/swipam-script/swipam.py as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

**Comment by alexkross** [comment]
Yes, example from README.md doesn't work as intended. Removed.
``ansible-inventory`` from playbook directory should works as usual.

Sorry for too late answer.
